# fly.toml app configuration file generated for upload-contabo on 2023-07-15T22:44:52+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "upload-contabo"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
